### ISSUE TITLE
[ Feature ] Pytorch Model to NCNN Model

### ISSUE THREAD

**Issue by iwubcode** [joeyballentine/chaiNNer#235]
As an AMD user, the automatic conversion from the pytorch model format to ncnn is really nice to have in cupscale.  For now I can use that tool and use any converted models in chaiNNER but it would nice to support something similar natively in chaiNNER.

I know this was in the readme but I wanted to capture it as an issue so someone would be more likely to work on it :)

**Comment by joeyballentine** [comment]
I was working on this in the past but wasn't able to get the package working quite right for it. It's difficult to get it working for Linux specifically. 

I'll come back to it at some point.

The issue is just that conversion from pytorch to ncnn isn't that simple, and the code that allows easy conversion isn't for python. So, the solution is to use temp files and the precompiled binaries (which is what cupscale does). The issue with this though is chainner supports more than just windows, which makes that kind of thing far more difficult thanks to all the varieties of Linux (and especially the pypi requirements to get a package published).

So, it'll be done at some point, but I don't know when.
