### ISSUE TITLE
[ Question ] Does NCNN node use RealESRGAN or ESRGAN?

### ISSUE THREAD

**Issue by iwubcode** [joeyballentine/chaiNNer#238]
I'm very new to upscaling, so apologies if this is a dumb question!

For cupscale, we have the option to use "RealESRGAN" or "ESRGAN" with NCNN.  RealESRGAN is faster but only supports 4x models (not sure if it's a limitation of the implementation or RealESRGAN).  Which one does chainner use?

**Comment by joeyballentine** [comment]
RealESRGAN is not faster than ESRGAN, it _is_ esrgan. It's the exact same architecture. 

Unless you mean the SRVGGNet type RealESRGAN models, those are a different architecture (xinntao called these the "anime video" models)

Anyway, NCNN mode in chainner does not require any specific architecture. Due to the way NCNN works, theoretically any SR architecture converted to NCNN works. That's why Waifu2x actually works with chaiNNer even though it's not implemented on the pytorch side.

**Comment by iwubcode** [comment]
Yeah the wording was confusing to me too.  I was just going off of cupscale's terminology.  I don't think it's a different model type?

The release notes for cupscale say:

> Added support for [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) - Similar to ESRGAN NCNN, much faster, but currently only works with 4x scale models
> Improved NCNN converter to work with Real-ESRGAN
> Added new options for ESRGAN-NCNN and RealESRGAN-NCNN

9.9s for a 512x512 image (RealESRGAN) vs 28.1s (ESRGAN) so it's quite a bit faster.

While chaiNNer doesn't have any statistics it outputs, timing it manually with a stopclock seems to give around similar speeds to RealESRGAN in cupscale so that's good enough for me.

Thanks!

**Comment by joeyballentine** [comment]
Cupscale just bundled the RealESRGAN binaries instead of actually using the raw NCNN code. ChaiNNer uses the generic NCNN code that can run anything.
