### ISSUE TITLE
ONNX runtime is not supported with a system Python version newer than 3.9.x

### ISSUE THREAD

**Issue by kimberly990** [joeyballentine/chaiNNer#660]
This is due to ONNX runtime not supporting 3.10.x and newer for the preferred 1.11 release.

**Comment by joeyballentine** [comment]
I'm not really sure why you opened an issue for this since there isn't anything I can even do about it.

**Comment by joeyballentine** [comment]
This specially is not fixable until onnxruntime gets support for 3.10. however, chainner could do a better job relaying the errors to the user. 

Since we just expect things to work as we expect the user to be using 3.9, we didn't really consider adding error parsing and having error popups for the dependency manager. This was obviously a bad oversight, so we should definitely communicate those kinds of errors to the user.

**Comment by RunDevelopment** [comment]
IMO, we should just drop 3.10. We already excluded it from CI tests, because it caused problems, so it's already partially dropped.

**Comment by joeyballentine** [comment]
Fixed as of v0.12.0
