### ISSUE TITLE
Better descriptions for certain nodes

### ISSUE THREAD

**Issue by kimberly990** [joeyballentine/chaiNNer#663]
Many nodes within chaiNNer could do with an overhaul of the descriptions to better clarify their functions. The Threshold nodes are a good example, as they only reiterate what the title explains. What does performing a threshold on an actually image mean?

The nodes I believe are included in this:

- All of the Image (Adjustments) nodes
- Normalize Normal Maps
- Add Caption

**Comment by RunDevelopment** [comment]
While I agree that we need to provide more information on what nodes do and how to use them (e.g. I have no idea what the Threshold nodes do), I don't think lengthy descriptions are the way to go.

I always thought of node descriptions (= the text you see while hovering over a node in the node selector panel) as small summaries of that node's functionality. I think providing detailed information/documentation in something larger than a tooltip would be better (#138).

Or we go the path that many IDEs also take and make super detailed tooltips. Though, it may be impossible to link different documentations that way due to the limitations of Chakra's tooltip. Not sure.
![image](https://user-images.githubusercontent.com/20878432/182024580-e874e31f-953d-49ad-a087-bcce81e95063.png)

**Comment by kimberly990** [comment]
`I always thought of node descriptions (= the text you see while hovering over a node in the node selector panel) as small summaries of that node's functionality`

I agree. That's the problem actually. Most of the nodes I listed don't actually explain what they do.

Regarding larger dialogs for detailed information, that'd be a great addition. How would you plan on implementing this visually?

**Comment by RunDevelopment** [comment]
> How would you plan on implementing this visually?

Just a popup. I think, I shared a screenshot a few months ago in the dev channel.

**Comment by RunDevelopment** [comment]
Also, what more do you want to say about nodes? I'm not sure what to add to e.g. the Opacity node ("Adjusts the opacity of an image.").

**Comment by kimberly990** [comment]
Hm. You're right, my bad. Those nodes in that category don't really need it other than Threshold. Threshold is the one that's the most unclear. I've been working with images a good portion of my life and I didn't even know what it meant.

Same goes for Normalize Normal Maps. I'm assuming it corrects normal maps to their proper colors to ensure they work in a game, but the description doesn't do much to clarify this. 

Ignore Add Caption and the rest of the Image (Adjustments) category, I was mistaken in including those.

**Comment by joeyballentine** [comment]
https://en.m.wikipedia.org/wiki/Thresholding_(image_processing)

**Comment by RunDevelopment** [comment]
> I'm assuming it corrects normal maps

A normal map is just a 2D array of normal surface vectors (normal meaning length 1 here). Normalize just means that we make sure that all normal vectors are actually length 1, since image operations and lossy compression can denormalize things.

I'm not sure what else to add to the description. "Normalize" is a [standard](https://registry.khronos.org/OpenGL-Refpages/gl4/html/normalize.xhtml) [term](https://www.wikihow.com/Normalize-a-Vector) when it comes to vectors.

**Comment by kimberly990** [comment]
We had discussed this topic on the Discord server before, I thought we had agreed this node specifically (Threshold) needed an expanded description. I'm not sure what to add as I have no experience with actually thresholding images.

As for the Normalize Normal Maps node, maybe just add a shortened description of what you just said @RunDevelopment. It should be short enough to fit into the tooltip without issue. "Ensures all normal vectors are a length of 1".

**Comment by joeyballentine** [comment]
It should have an expanded description. I think all nodes should have more of an explanation rather than just saying they do the thing they're named after.

However, similar to calling the node connections edges, this is another case where we're just using a standard term for something. Doesn't mean we shouldn't try to explain it for people that don't know what it is, but it's not like it's an uncommon image processing term. The description is useless right now yes, but a quick google search should clear up what it does for anyone who is unfamiliar with it. Same goes for pretty much all the other nodes. 

Users shouldn't have to do that though. I think short term adding some more info to the descriptions would be good, and long term implementing the in depth expanded descriptions for each one would be good as well. 

As for how we do the expanded descriptions, I'm still of the opinion that we should not do it via the markdown files you wanted to do @RunDevelopment. We can talk more about that in discord.

**Comment by RunDevelopment** [comment]
> I'm still of the opinion that we should not do it via the markdown files

Honestly, same. I still think MD is the way to go, but storing it in files has some downsides. I like the alternative of writing MD in Python strings even less, though.

**Comment by joeyballentine** [comment]
Well, we'd need a way to add formatting like italics and bolding. Either we'll be making our own syntax for that or using an existing one.

But I think we should let the code do almost all of the actual formatting. In my opinion, every node should have a short description (for the hover tooltip) and a long description (for the expanded stuff), and all input should have their own descriptions and type information listed. 

Inputs can have default descriptions that are generic. Something like "A numeric value between 0-100" for example. But then maybe we could use something like a .with_description function to add better descriptions to each input. 

Another thing I wanted to do was have a way to view input descriptions on an input itself, in certain cases. Like the tile size dropdown I was working on. I think being able to remind yourself about what a specific input is without having to go back to looking at the full node stuff would be great. Or I guess we could just add a help section to the context menu. Idk exactly. 

But my main thing is that we should be breaking up each part of the full documentation and building it into a big thing so it's easier to reuse specific parts and update formatting across the board.

**Comment by RunDevelopment** [comment]
Was this not resolved by #681?

**Comment by RunDevelopment** [comment]
@joeyballentine @kimberly990

**Comment by joeyballentine** [comment]
I don't know if that really counts as what this ticket wanted

**Comment by kimberly990** [comment]
#681 did 99% of what I wanted from this. Having in-depth descriptions with formatting would be great, but that wasn't my original intention with this ticket

**Comment by joeyballentine** [comment]
In that case, consider this closed.
