### ISSUE TITLE
after installed the 0.11.1 exe on windows,failed to fetch

### ISSUE THREAD

**Issue by yueyunze** [joeyballentine/chaiNNer#749]
![1](https://user-images.githubusercontent.com/21197554/185375870-4bb919df-abc7-45c5-b0a2-9281d83de5e8.png)

**Comment by RunDevelopment** [comment]
Hello @yueyunze!

Could you please share your logs with us? In chainner's menu, click _Help_ > _Open logs folder_, create a zip with `main.log` and `renderer.log`, and [attach the zip file to a comment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files).

**Privacy information**: These log files contain file paths of chainner's files. The file paths may contain the name of your account (e.g. `Users/michael/...`). If your account is your real name, and you are not comfortable sharing, then do not upload your logs.

**Comment by theflyingzamboni** [comment]
Or make a copy and do a Find/Replace on the info you want to censor.

**Comment by yueyunze** [comment]
[main.log](https://github.com/joeyballentine/chaiNNer/files/9378871/main.log)
That means I don't have the dependency.Why does chaiNNer not use admin python route?
![image](https://user-images.githubusercontent.com/21197554/185533438-ada2610c-e3b5-41cf-bde9-53271e58f02d.png)
Python binary for the pc is:
![1](https://user-images.githubusercontent.com/21197554/185533696-ddb2f149-48a9-43dd-869f-1f3bf847ae98.jpg)
But chaiNNer detect the  Final Python binary is: 
C:\Users\Administrator\AppData\Roaming\chaiNNer\python\python\python.exe
When I use the pip list --format=json --disable-pip-version-check command line in CMD,that shows include all depencies.
But chaiNNer  even not found it in the system path route.
![2](https://user-images.githubusercontent.com/21197554/185534096-0260add2-4b6f-4475-b1f8-5ab4741442c9.jpg)
chaiNNer only found it in "its" Final Python binary .
Some suggestion: When installing the program,showing that big Software Icon for users but not shown those installation dialogs （at least the user can choose whether to display ) is a very bad design for GUI,unless it is a sophisticated software that users can truly achieve one-click installation.Users don't like waiting that long time and finally show "Exit" without any warning box popping up.

**Comment by joeyballentine** [comment]
Hi. I have fixed this issue and it should be getting released tomorrow. 

As for why we install things automatically, it's the alternative to bundling everything with chaiNNer. Besides the fact that due to licensing issues we can't necessarily bundle everything we need, it would also suck to have to redownload everything related to the python environment every time. So we download the integrated python and install the required dependencies on first startup. It's not a perfect solution but it works well enough.

The reason we don't encourage you to use your system python installation (even though we do allow you to toggle it in the settings) is because different versions of packages can cause problems, either if they're too up to date or too old. Not only that, but using too old or too new of a python version can also have issues. By using the integrated python we can control an isolated environment where we can guarantee everything python related works.

As for this crash, it was caused by a fix I did for another issue a while back. Basically some people have a global environment variable which was causing some issues by overriding a python path, so I had chaiNNer ignore that variable internally. The problem is, if you don't have that variable in the first place, it crashes. So it was an easy enough fix, and should be released tomorrow.

**Comment by joeyballentine** [comment]
Ah, I misunderstood your comment. I thought you were saying it was bad to install the things in general, but I now see you mean that chaiNNer does not display the information about the dependency installs, so it can just take a while with no information being displayed. I can definitely make that UX better.

**Comment by joeyballentine** [comment]
@yueyunze, could you please try the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.2) and see if it resolves your issues?

**Comment by yueyunze** [comment]
@joeyballentine solved. After configuring PIP and installing global agent，0.11.2 works!Thx!
