### ISSUE TITLE
Dummy-proxy node

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [joeyballentine/chaiNNer#781]
Even with the substance designer, I noticed a problem when I need to switch one source image for many nodes, then I have to change links for each, so I began to use a doing nothing proxy node there.
Here the situation is similar, now I began to use HUE & SATURATION for this.
I can continue to do this, but it doesn't seem right in terms of architecture/design.

Example:
![изображение](https://user-images.githubusercontent.com/4449851/185742981-e8f7c361-7bd4-4779-8881-cd7fe955c93e.png)

**Comment by RunDevelopment** [comment]
That sounds like a good idea. We could add a node that accepts any value (not just images) and returns it as is.

I'm just not sure what to name it. "[Identity](https://en.wikipedia.org/wiki/Identity_function)" would be the mathematical term, but I'm not sure whether users will recognize this term.

---

You actually picked the ideal node as workaround in the meantime. H&S actually optimizes the case where you don't actually change the image and will return the input image as is with no cost whatsoever.

**Comment by 0x4E69676874466F78** [comment]
@RunDevelopment 
> I'm just not sure what to name it. "[Identity](https://en.wikipedia.org/wiki/Identity_function)" would be the mathematical term, but I'm not sure whether users will recognize this term.

I think few people will understand without a description.
Alternatively, it can also be called "passthrough node".

**Comment by RunDevelopment** [comment]
We have a feature called "passthrough" planned already (#373), so we can't use that name. Yes, they are totally different, but this would get confusing.

**Comment by 0x4E69676874466F78** [comment]
@RunDevelopment as I understand it, it is about the mode of any node when it is turned off and just has to skip further (do not stop chain). I don't see a conflict here.

**Comment by RunDevelopment** [comment]
The problem is that they have the same name. I wouldn't be able to tell people: "You can solve this by using passthrough," because it wouldn't be 100% clear which one I meant. Vocabulary should be unambiguous if possible.

Regarding alternative names for this node: Since its purpose is to join/bundle edges, so you can change the source of multiple connected inputs at once, maybe we could take inspiration from that.

**Comment by joeyballentine** [comment]
I think we might need a whole different type of node here that is completely different from anything else. Like something small that just has a handle on each side that accepts anything. We could call it a bridge or a splitter or something

**Comment by RunDevelopment** [comment]
I think blender allows you to minimize nodes like this:

![image](https://user-images.githubusercontent.com/20878432/185749044-b6fa968b-0000-4af3-a9b1-33ab81de3fd5.png)

It would be pretty useful to have that as a general feature instead of a special property for one node. Other nodes (e.g. Invert color) would also benefit from this.
