### ISSUE TITLE
Allow Video Frame Iterator blocks run in batches instead of series.

### ISSUE THREAD

**Issue by iamwavecut** [joeyballentine/chaiNNer#858]
**Motivation**
I'm using chaiNNer to restore videos and gifs, and I love it. But it's slow in that kind of workflow.

**Description**
Now, chaiNNer Video Frame Iterator runs every frame iteration serially, which adds a lot of wasted time for model loading/releasing for every iterated frame.
My proposal: Run every "block" batched.
I want EACH model (or filter, block, etc) in this chain to process 100 frames at a time, which leads us to a 1*1 model loading time, instead of 1*100.
The only thing that gets broken in this kind of execution plan is the image preview is available only for the running block.

**Alternatives**
Make it optional, as a VFI setting or something.

**Comment by joeyballentine** [comment]
We can't trivially do this due to typically VRAM constraints when upscaling. We would need to implement some sort of multithreading VRAM usage lock, and I have no idea how to do that. Without it, you'd run out of memory constantly when trying to do anything. It would be nice though, because it would totally be possible for small images and smaller models, but without any way to prevent OOM errors when doing too much at once there really isn't a good way.

**Comment by iamwavecut** [comment]
A think you misunderstood me, sorry for my clumsy English.

I'm not talking about parallelization, not to process 100 frames in 1 job. 

What I mean is to load the model once, then do 100 frames sequentially with it, then release model VRAM, move those 100 intermediate frames to the next block input, and repeat.

**Comment by joeyballentine** [comment]
You can already do that. Just keep the model outside of the iterator and attach it to the upscale node that is inside the iterator
