### ISSUE TITLE
No Output for PyTorch Convert to NCNN

### ISSUE THREAD

**Issue by trancefusiondesign** [joeyballentine/chaiNNer#943]
I don't have the option to output a conversion. Is this because I'm on an Intel MacBook Pro?

![Screen Shot 2022-09-13 at 1 23 49 PM](https://user-images.githubusercontent.com/68971420/190005173-de45e65d-4682-49b9-8b6b-aa61d1b06e44.png)

**Comment by joeyballentine** [comment]
Make sure you have onnx installed. Conversion to ncnn goes through onnx and therefore is required for it to work. I need to make that more obvious instead of just hiding the outputs, so that will be fixed in a later version.

You should be able to install onnx on a Mac so long as it's not m1, so I think you're fine. Try that and see if it works

**Comment by trancefusiondesign** [comment]
Thank you! That worked. :)

![Screen Shot 2022-09-13 at 1 45 50 PM](https://user-images.githubusercontent.com/68971420/190006067-f99e5281-7666-494a-95e3-06805f0c1b78.png)
